### ISSUE TITLE
Symbol / String confusion for hash for minitest

### ISSUE THREAD

**Issue by jmarrec** [NREL/OpenStudio-measure-tester-gem#78]
bundle exec openstudio:rubocop

```
NoMethodError: undefined method `>' for nil:NilClass
/home/julien/Software/Others/openstudio_gems/OpenStudio-measure-tester-gem/lib/openstudio_measure_tester/openstudio_testing_result.rb:163:in `exit_code'
/home/julien/Software/Others/openstudio_gems/OpenStudio-measure-tester-gem/lib/openstudio_measure_tester/runner.rb:110:in `post_process_results'
/home/julien/Software/Others/openstudio_gems/OpenStudio-measure-tester-gem/lib/openstudio_measure_tester/runner.rb:176:in `run_rubocop'
/home/julien/Software/Others/openstudio_gems/OpenStudio-measure-tester-gem/lib/openstudio_measure_tester/rake_task.rb:45:in `block (3 levels) in setup_subtasks'
/home/julien/Software/Others/openstudio_gems/openstudio-bem-to-surrogate-gem/.bundle/ruby/2.7.0/gems/rake-13.2.1/exe/rake:27:in `<top (required)>
```

**Comment by jmarrec** [comment]
https://github.com/NREL/OpenStudio-measure-tester-gem/blob/14659ef904019789f651a890bc56d2324d725805/lib/openstudio_measure_tester/openstudio_testing_result.rb#L163

When I reach that code, I have `'total_failures'`  (String) as a key.
